#!/bin/bash
#$ -S /bin/bash
#$ -N 03_smoove
#$ -cwd
#$ -pe OpenMP 4
#$ -l s_vmem=8G -l mem_req=8G
#$ -o logs/03/$TASK_ID.log
#$ -e logs/03/$TASK_ID.log

# 使い方
# qsub -t 1-100:1 -tc 10 qsubs/03_smoove_genotype.qsub \
#   data/sample_cram.txt \
#   data/hg38.fa \
#   results/02/merged.sites.vcf.gz


set -euo pipefail


# 位置引数
SAMPLE_FILE=$1
REF=$2
SITE_VCF=$3


# サンプル名とCRAMパス
read SAMPLE CRAM < <(sed -n "${SGE_TASK_ID}p" "$SAMPLE_FILE")


# 実行
mkdir -p logs/03

bash scripts/03_smoove_genotype.sh \
  --ref "$REF" \
  --cram "$CRAM" \
  --site_vcf "$SITE_VCF" \
  --sample "$SAMPLE" \
  --threads "$NSLOTS"
