#!/bin/bash
#$ -S /bin/bash
#$ -N 04_ehdn
#$ -cwd
#$ -pe OpenMP 4
#$ -l s_vmem=8G -l mem_req=8G
#$ -o logs/04/$TASK_ID.log
#$ -e logs/04/$TASK_ID.log

set -euo pipefail


# 位置引数
PROBANDS=$1
CONTROLS=$2
PROBAND_RELATIVE_PAIRS=$3
PREFIX=$4


# サンプル名とCRAMパス
read PROBAND < <(sed -n "${SGE_TASK_ID}p" "$PROBANDS")


# 実行
mkdir -p logs/04
mkdir -p results/04/$PROBAND

awk \
  -v PROBAND="${PROBAND}" \
  '$1==PROBAND && $2!=PROBAND {
    print $2
  }' "$PROBAND_RELATIVE_PAIRS" \
  > results/04/$PROBAND.other_family_members.txt

conda run -n ehdn_env \
  scripts/04_add_allele_count.py \
    --proband              "$PROBAND" \
    --other_family_members results/04/$PROBAND.other_family_members.txt \
    --controls             "$CONTROLS" \
    --outlier_locus        results/03/$PREFIX.outlier_locus.annotated.tsv \
    --outlier_motif        results/03/$PREFIX.outlier_motif.tsv \
    --out                  results/04/$PROBAND \
    > logs/04/$PROBAND.log 2>&1 # conda runはこのようにしないとエラーを捉えられないことがあるらしい
